return {
  --Theme & Appearance
  'GlennLeo/cobalt2',
  'ellisonleao/gruvbox.nvim',
  'NLKNguyen/papercolor-theme',
  'nvim-lualine/lualine.nvim',
  "b0o/incline.nvim",
  { "rose-pine/neovim", as = "rose-pine" },
  'projekt0n/github-nvim-theme',
  'sainnhe/sonokai',
  "lukas-reineke/indent-blankline.nvim",
  'xiyaowong/nvim-transparent',
  'GustavoPrietoP/doom-themes.nvim',
  'folke/tokyonight.nvim',
  'nvim-tree/nvim-web-devicons',
  'akinsho/bufferline.nvim',
  'Mofiqul/vscode.nvim',
  'catppuccin/nvim',


  --Funtionalities
  'lervag/vimtex',
  'rcarriga/nvim-notify',
  'hedyhli/outline.nvim',
  'MunifTanjim/nui.nvim',
  "folke/noice.nvim",
  'ggandor/leap.nvim',
  'voldikss/vim-floaterm',
  'nvim-tree/nvim-tree.lua',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim', tag = '0.1.8',
  "nvim-telescope/telescope-file-browser.nvim",
  "windwp/nvim-autopairs",
  {'nvim-treesitter/nvim-treesitter' , build= ":TSUpdate"},
  'goolord/alpha-nvim',
  {'neoclide/coc.nvim', branch = 'release'},
  'kevinhwang91/promise-async',
  'kevinhwang91/nvim-ufo',
}
